language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
install:
- pip install -U platformio
script:
- "./generate_secrets.sh"
- platformio run
env:
  global:
    secure: RRO6VkI3+w4mgLjQGdC7wTagNAcEaRr9G095u5aFKp6OJeNIr3wL9bD2E/WiJ25/tldktl+4G41WPhRTbVWiuIAZlagY/7iHXlmCxTNFJC7wYGudNWWiCAsVU2ERoO98lRTn9Z4+KMlx0s1KalSP7a6PWjKfv7gjR8plaL86VEjJ6ZoJ75YQ4al8CBiDnTDNUKZXQfHPZs6Rl4DSSZ4DvZXsweqlN4g15+SbR9vsiPslQ6sIFdV/jmTZwwiv7YuoqZzd3+kdugkP+zxwL6t15rHnuC7T8NYX0mUSSopAhyiCAhwc/DHcPaOvKqeJtp9z5wLa4UNC7SfjnkY5NAITRMv70kmHMOC/TDxs9KhLzIfqUuDe5DZGi7aUjPebgMBhTchczZCI7Dn1gkYfyVRQdyToa2xvI4X1kU+WuUX9D79Hr08n/lKIIo34+ZSU0UsEg2K8SkkCRGpWZOs2G/I/rozkS3ykNxuNvsuTFAMNisR6yOsF52DATEHOx2MORHxct4Lg1DvkIIpqxFpIqIj8vvXO7fV74JVHkKCAoIFWvMUqx29w6qDawjPRkQNQgbszUwAflAOTW/0ejPth0YKGXFO5Pl9MJoUzofAdkBvcMPFr/OJUxS/rED+693xoU5pwEpQwy0hdN13D7T0+ET2l3jUsiLkk/GVTcX8vCm6YR74=
